[package]
name = "sol-ver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.9.2"
sol-ver-interface = { version = "^0", path = "../interface" }


[dev-dependencies]
solana-program-test = "3.0.0"